/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary": "#bcc7de",
        "tertiary-fixed-dim": "#ddb7ff",
        "on-secondary-fixed": "#111c2d",
        "on-tertiary-fixed": "#2c0051",
        "surface-container-lowest": "#060e20",
        "outline": "#908fa0",
        "on-error-container": "#ffdad6",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-primary-fixed": "#07006c",
        "surface-container": "#171f33",
        "secondary-fixed-dim": "#bcc7de",
        "on-primary-fixed-variant": "#2f2ebe",
        "error": "#ffb4ab",
        "surface-bright": "#31394d",
        "outline-variant": "#464555",
        "primary-fixed": "#e1e0ff",
        "surface-dim": "#0b1326",
        "on-background": "#dae2fd",
        "on-tertiary-container": "#fff6ff",
        "on-surface": "#dae2fd",
        "surface-tint": "#c0c1ff",
        "primary-fixed-dim": "#c0c1ff",
        "on-surface-variant": "#c7c4d7",
        "primary-container": "#5d60eb",
        "on-tertiary": "#490080",
        "on-tertiary-fixed-variant": "#6900b3",
        "tertiary-fixed": "#f0dbff",
        "surface-variant": "#2d3449",
        "primary": "#c0c1ff",
        "tertiary": "#ddb7ff",
        "on-primary-container": "#faf7ff",
        "surface-container-high": "#222a3d",
        "surface-container-highest": "#2d3449",
        "on-primary": "#1000a9",
        "secondary-fixed": "#d8e3fb",
        "on-secondary-container": "#aeb9d0",
        "secondary-container": "#3e495d",
        "on-secondary": "#263143",
        "tertiary-container": "#9945e8",
        "on-secondary-fixed-variant": "#3c475a",
        "inverse-on-surface": "#283044",
        "surface": "#0b1326",
        "surface-container-low": "#131b2e",
        "inverse-primary": "#494bd6",
        "background": "#0b1326",
        "inverse-surface": "#dae2fd"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["'Plus Jakarta Sans'", "sans-serif"],
        "body": ["'Plus Jakarta Sans'", "sans-serif"],
        "label": ["'Plus Jakarta Sans'", "sans-serif"]
      }
    },
  },
  plugins: [],
}
